apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    repoURL: https://github.com/Grbic14/gitops-helm-chart.git
    targetRevision: main
    path: charts/demoapp
    helm:
      values: |-
        image:
          repository: nginx
          tag: "1.28"
        replicaCount: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
